version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: client
                        dockerfile: Dockerfile
                        args:
                                - HOST_NAME=${HOST_NAME}
                environment:
                        - NODE_ENV=production
                env_file:
                        - .env
                volumes:
                        - ./client_build:/home/node/app/build_final
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.3
        essw_node_server:
                user: node
                build:
                        context: server
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.4
        essw_nginx:
                user: nginx
                build:
                        context: nginx
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                        - 443:443
                environment:
                        - HOST_NAME=localhost
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.2
                volumes:
                        - ./user_certificates:/ssl_gen/user_nginx_certificates
                        - ./client_build/build:/usr/share/nginx/html/react
networks:
        frontend_connection:
                name: frontend_connection
                driver: bridge
        backend_connection:
                ipam:
                        driver: default
                        config:
                                - subnet: "172.60.0.0/24"
                                  gateway: "172.60.0.1"