version: '3.9'
services:
        essw_node_app:
                user: node
                build:
                        context: node_docker
                        dockerfile: Dockerfile
                ports:
                        - 8080:8080
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=8080
                networks:
                        - default
                        - backend
networks:
        backend:
                name: backend_connection
                driver: bridge