version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: client
                        dockerfile: Dockerfile
                        target: ${CLIENT_TARGET}
                env_file:
                        - .env
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.3
        essw_node_server:
                user: node
                build:
                        context: server
                        dockerfile: Dockerfile
                env_file:
                        - .env
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.4
        essw_nginx:
                user: nginx
                build:
                        context: nginx
                        dockerfile: Dockerfile
                        args:
                                - HOST_NAME=${HOST_NAME}
                ports:
                        - 80:80
                        - 443:443
                env_file:
                        - .env
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.2
networks:
        frontend_connection:
                name: frontend_connection
                driver: bridge
        backend_connection:
                ipam:
                        driver: default
                        config:
                                - subnet: "172.60.0.0/24"
                                  gateway: "172.60.0.1"