version: '3.9'
services:
  essw-client:
    image: esswreg.azurecr.io/essw-client
    user: node
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - 'HOST_NAME=${HOST_NAME}'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - 'azure:/home/node/app/build_final'
    networks:
      backend_connection:
        ipv4_address: 172.60.0.3

  essw-server:
    image: esswreg.azurecr.io/essw-server
    user: node
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      backend_connection:
        ipv4_address: 172.60.0.4

  essw-nginx:
    image: esswreg.azurecr.io/essw-nginx
    domainname: esswdemo
    user: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - 'HOST_NAME=${HOST_NAME}'
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    networks:
      backend_connection:
        ipv4_address: 172.60.0.2
    volumes:
      #- 'azure:/ssl_gen/user_nginx_certificates'
      - 'azure:/usr/share/nginx/html'

networks:
  backend_connection:
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/24
          gateway: 172.60.0.1

volumes:
    azure:
      driver: azure_file
      driver_opts:
          share_name: esswshare
          storage_account_name: esswstore
