version: '3.9'
services:
  essw-client:
    image: esswreg.azurecr.io/essw-client
    user: node
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - 'HOST_NAME=${HOST_NAME}'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.1G'
      restart_policy:
        condition: any
        max_attempts: 5
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - 'azure:/home/node/app/build_final'
    networks:
      backend_connection:
        ipv4_address: 192.168.0.3

  essw-server:
    container_name: backend
    image: esswreg.azurecr.io/essw-server
    user: node
    build:
      context: server
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5G'
      restart_policy:
        condition: any
        max_attempts: 5
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      backend_connection:
        ipv4_address: 192.168.0.4

  essw-nginx:
    container_name: proxy
    image: esswreg.azurecr.io/essw-nginx
    domainname: esswdemo
    user: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - 'HOST_NAME=${HOST_NAME}'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5G'
      restart_policy:
        condition: any
        max_attempts: 5
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    networks:
      backend_connection:
        ipv4_address: 192.168.0.2
    volumes:
      - 'azure:/usr/share/nginx/html'


networks:
  backend_connection:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
    azure:
      driver: azure_file
      driver_opts:
          share_name: esswshare
          storage_account_name: esswstore
