version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: client
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.3
        essw_node_server:
                user: node
                build:
                        context: server
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.4
        essw_nginx:
                user: nginx
                build:
                        context: nginx
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                        - 443:443
                environment:
                        - HOST_NAME=the-index.xyz
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.2
                volumes:
                        - ./certbot/www:/var/www/certbot:ro
                        - ./certbot/conf/live/:/var/ssl/:ro
        certbot: 
                build:
                        context: certbot
                        dockerfile: Dockerfile
                environment:
                        - HOST_NAME=the-index.xyz
                volumes:
                        - ./certbot/www:/var/www/certbot/:rw
                        - ./certbot/conf:/etc/letsencrypt/:rw
                command: certonly -v --preferred-challenges http -d the-index.xyz --non-interactive --agree-tos -m petribayley@gmail.com --webroot -w /var/www/certbot/
                #profiles:
                        #- donotstart

networks:
        frontend_connection:
                name: frontend_connection
                driver: bridge
        backend_connection:
                ipam:
                        driver: default
                        config:
                                - subnet: "172.60.0.0/24"
                                  gateway: "172.60.0.1"