version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: client
                        dockerfile: Dockerfile
                ports:
                        - 8081:3000
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=8081
                networks:
                        - backend
        essw_node_server:
                user: node
                build:
                        context: server
                        dockerfile: Dockerfile
                ports:
                        - 8082:8082
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=8082
                networks:
                        - backend
        essw_nginx:
                user: nginx
                build:
                        context: nginx
                        dockerfile: Dockerfile
                volumes:
                        - ./certbot/www:/var/www/certbot/:ro
                ports:
                        - 80:80
                        - 443:80
                environment:
                        - NGINX_HOST=localhost.com
                        - NGINX_PORT=80
                networks:
                        - backend
                        - default
        certbot:
                image: certbot/certbot:latest
                volumes:
                        - ./certbot/www/:/var/www/certbot/:rw
networks:
        backend:
                name: backend_connection
                driver: bridge