version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: docker_node_client
                        dockerfile: Dockerfile
                ports:
                        - 80:8081
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=80
                networks:
                        - backend
        essw_node_server:
                user: node
                build:
                        context: docker_node_server
                        dockerfile: Dockerfile
                ports:
                        - 80:8082
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=80
                networks:
                        - backend
        essw_nginx:
                user: nginx
                image: nginx
                volumes:
                        - ./certbot/www:/var/www/certbot/:ro
                ports:
                        - 80:80
                        - 443:433
                environment:
                        - NGINX_HOST=localhost.com
                        - NGINX_PORT=80
                networks:
                        - backend
                        - default
        certbot:
                image: certbot/certbot:latest
                volumes:
                        - ./certbot/www/:/var/www/certbot/:rw
networks:
        backend:
                name: backend_connection
                driver: bridge