version: '3.9'
services:
        essw_node_client:
                user: node
                build:
                        context: client
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=8081
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.3
        essw_node_server:
                user: node
                build:
                        context: server
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                        - NODE_PORT=8082
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.4
        essw_nginx:
                user: nginx
                build:
                        context: nginx
                        dockerfile: Dockerfile
                volumes:
                        - ./certbot/www:/var/www/certbot/:ro
                ports:
                        - 80:80
                        - 443:80
                environment:
                        - NGINX_HOST=localhost.com
                        - NGINX_PORT=80
                networks:
                        backend_connection:
                                ipv4_address: 172.60.0.2
        certbot:
                image: certbot/certbot:latest
                volumes:
                        - ./certbot/www/:/var/www/certbot/:rw
networks:
        frontend_connection:
                name: frontend_connection
                driver: bridge
        backend_connection:
                ipam:
                        driver: default
                        config:
                                - subnet: "172.60.0.0/24"
                                  gateway: "172.60.0.1"