name: docker-compose-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
      name: Checkout
      uses: actions/checkout@v2
      - 
      name: Setup Environment
      run: |
        mv example.env .env
      - 
      name: Docker build
      run : |
        docker compose build