name: run-server-tests

on:
  push:
    branches:
      - main
    paths:
      - server/**
  pull_request:
    paths:
      - server/**

jobs:
  test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test
